/**
 * Affiliate Bookings Hooks
 *
 * React Query hooks for fetching bookings generated by affiliate's referral links.
 */

'use client';

import { useQuery } from '@tanstack/react-query';
import { bookingsApi } from '../api/bookings.api';
import type { BookingFilters } from '../types';

/**
 * Hook to fetch affiliate bookings
 *
 * Returns bookings generated by the user's referral links.
 * User must have canRefer capability.
 */
export function useAffiliateBookings(filters?: BookingFilters) {
  return useQuery({
    queryKey: ['bookings', 'affiliate', filters],
    queryFn: () => bookingsApi.getAffiliateBookings(filters),
    staleTime: 30 * 1000, // 30 seconds
    gcTime: 10 * 60 * 1000, // 10 minutes
  });
}

/**
 * Hook to fetch affiliate booking stats
 *
 * Returns summary statistics (total, active, revenue).
 */
export function useAffiliateBookingStats() {
  return useQuery({
    queryKey: ['bookings', 'affiliate', 'stats'],
    queryFn: () => bookingsApi.getAffiliateStats(),
    staleTime: 60 * 1000, // 1 minute
    gcTime: 10 * 60 * 1000,
  });
}
