import { apiClient } from '@/lib/api/client';
import type {
  CreateBookingRequest,
  CreateBookingResponse,
  BookingQuote,
  BookingDto,
  BookingFilters,
  BookingStats,
} from '../types';

/**
 * Bookings API client
 */
export const bookingsApi = {
  // ==========================================
  // PUBLIC ENDPOINTS (for guests)
  // ==========================================

  /**
   * Create a new booking (public)
   * Converts string IDs to numbers to match backend DTO (Long types)
   */
  async create(request: CreateBookingRequest): Promise<CreateBookingResponse> {
    // Transform string IDs to numbers for backend compatibility
    // Backend CreateBookingRequest expects Long for referralLinkId and propertyId
    const referralLinkId = Number(request.referralLinkId);
    const propertyId = Number(request.propertyId);

    // Defensive validation: reject non-numeric IDs before sending to backend
    if (isNaN(referralLinkId) || referralLinkId <= 0) {
      throw new Error('Invalid referral link ID. Please reload the page and try again.');
    }
    if (isNaN(propertyId) || propertyId <= 0) {
      throw new Error('Invalid property ID. Please reload the page and try again.');
    }

    const payload = {
      ...request,
      referralLinkId,
      propertyId,
    };

    const { data } = await apiClient.post<CreateBookingResponse>(
      '/api/public/bookings',
      payload
    );
    return data;
  },

  /**
   * Get a quote for a booking (calculate total price)
   */
  async getQuote(
    propertyId: string,
    startDate: string,
    endDate: string
  ): Promise<BookingQuote> {
    const { data } = await apiClient.get<BookingQuote>('/api/public/bookings/quote', {
      params: {
        propertyId,
        startDate,
        endDate,
      },
    });
    return data;
  },

  /**
   * Check availability for a property
   */
  async checkAvailability(
    propertyId: string,
    startDate: string,
    endDate: string
  ): Promise<boolean> {
    try {
      await apiClient.get('/api/public/bookings/check-availability', {
        params: {
          propertyId,
          startDate,
          endDate,
        },
      });
      return true; // Available
    } catch (error) {
      return false; // Not available
    }
  },

  // ==========================================
  // USER ENDPOINTS (AFFILIATE role)
  // ==========================================

  /**
   * Get bookings for affiliate (bookings generated by my referral links)
   */
  async getAffiliateBookings(filters?: BookingFilters): Promise<BookingDto[]> {
    const { data } = await apiClient.get<BookingDto[]>('/api/v1/bookings/affiliate', {
      params: filters,
    });
    return data;
  },

  /**
   * Get stats for affiliate bookings
   */
  async getAffiliateStats(): Promise<BookingStats> {
    const { data } = await apiClient.get<BookingStats>('/api/v1/bookings/affiliate/stats');
    return data;
  },

  // ==========================================
  // USER ENDPOINTS (HOST role)
  // ==========================================

  /**
   * Get bookings for host (bookings on my properties)
   */
  async getHostBookings(filters?: BookingFilters): Promise<BookingDto[]> {
    const { data } = await apiClient.get<BookingDto[]>('/api/v1/bookings/host', {
      params: filters,
    });
    return data;
  },

  /**
   * Get stats for host bookings
   */
  async getHostStats(): Promise<BookingStats> {
    const { data } = await apiClient.get<BookingStats>('/api/v1/bookings/host/stats');
    return data;
  },

  // ==========================================
  // SHARED ENDPOINTS (USER - both roles)
  // ==========================================

  /**
   * Get booking by ID (requires permission)
   */
  async getBookingById(id: number): Promise<BookingDto> {
    const { data } = await apiClient.get<BookingDto>(`/api/v1/bookings/${id}`);
    return data;
  },

  // ==========================================
  // ADMIN ENDPOINTS (already implemented in admin feature)
  // ==========================================
  // See: src/features/admin/bookings/api/admin-bookings.api.ts
};
